from finbot.core.errors import FinbotError


class WorkflowError(FinbotError):
    pass
